Fix NPE in NetdResponseCode.InterfaceClassActivity
Under circumstances the 4th param is null and causes NPE.
Exception looks like this in logcat:
E/NetdConnector( 1086): Error handling '613 IfaceClass idle (null)':
java.lang.NumberFormatException: Invalid int: "(null)"

Change-Id: Id1bbbeeec8452e7103c4213be7b3029c6d36fa55